import { defineElement } from '@st-lib/render'

const namespaceURI = 'http://www.w3.org/1998/Math/MathML'

export const maction = defineElement(['maction', namespaceURI])
export const math = defineElement(['math', namespaceURI])
export const menclose = defineElement(['menclose', namespaceURI])
export const merror = defineElement(['merror', namespaceURI])
export const mfenced = defineElement(['mfenced', namespaceURI])
export const mfrac = defineElement(['mfrac', namespaceURI])
export const mglyph = defineElement(['mglyph', namespaceURI])
export const mi = defineElement(['mi', namespaceURI])
export const mlabeledtr = defineElement(['mlabeledtr', namespaceURI])
export const mmultiscripts = defineElement(['mmultiscripts', namespaceURI])
export const mn = defineElement(['mn', namespaceURI])
export const mo = defineElement(['mo', namespaceURI])
export const mover = defineElement(['mover', namespaceURI])
export const mpadded = defineElement(['mpadded', namespaceURI])
export const mphantom = defineElement(['mphantom', namespaceURI])
export const mroot = defineElement(['mroot', namespaceURI])
export const mrow = defineElement(['mrow', namespaceURI])
export const ms = defineElement(['ms', namespaceURI])
export const mspace = defineElement(['mspace', namespaceURI])
export const msqrt = defineElement(['msqrt', namespaceURI])
export const mstyle = defineElement(['mstyle', namespaceURI])
export const msub = defineElement(['msub', namespaceURI])
export const msubsup = defineElement(['msubsup', namespaceURI])
export const msup = defineElement(['msup', namespaceURI])
export const mtable = defineElement(['mtable', namespaceURI])
export const mtd = defineElement(['mtd', namespaceURI])
export const mtext = defineElement(['mtext', namespaceURI])
export const mtr = defineElement(['mtr', namespaceURI])
export const munder = defineElement(['munder', namespaceURI])
export const munderover = defineElement(['munderover', namespaceURI])
export const semantics = defineElement(['semantics', namespaceURI])
